[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "apscheduler>=3.11.0",
    "flask>=3.1.2",
    "networkx>=3.5",
    "pandas>=2.3.2",
    "plotly>=6.3.0",
]
